//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AssignmentEFProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class Department
    {
        public int dpm_id { get; set; }
        public string dpm_name { get; set; }
    }
}
