// <auto-generated />
using Day19Project.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Day19Project.Migrations
{
    [DbContext(typeof(ShopContext))]
    partial class ShopContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Day19Project.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Pic")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 101,
                            Description = "Drop down any product description here.",
                            Name = "Super Fresh Banana",
                            Pic = "/images/Banana.jpg",
                            Price = 88.879999999999995
                        },
                        new
                        {
                            Id = 102,
                            Description = "Drop down any product description here.",
                            Name = "Super Crunchy Biscuit",
                            Pic = "/images/Biscuit.jpg",
                            Price = 12.880000000000001
                        },
                        new
                        {
                            Id = 103,
                            Description = "Drop down any product description here.",
                            Name = "No Brand Polo-T",
                            Pic = "/images/PoloT.jpg",
                            Price = 23.879999999999999
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
